    - name: 'update config file with host ip'
      lineinfile:
        path: /etc/rancher/k3s/k3s.yaml 
        regexp: 'server: https://127.0.0.1:6443'
        line: '    server: https://{{ ansible_default_ipv4.address }}:6443'
        state: present


    - name: copy over kubectl config file
      fetch: 
        src: /etc/rancher/k3s/k3s.yaml 
        dest: ../assets/
        flat: yes
