- hosts: pi-poe
  become: yes
  tasks:
    - lineinfile:
        path: /boot/firmware/usercfg.txt
        state: present
        regexp: '^dtoverlay=rpi-poe'
        line: 'dtoverlay=rpi-poe'
    - lineinfile:
        path: /boot/firmware/usercfg.txt
        state: present
        regexp: '^dtparam=poe_fan_temp0'
        line: 'dtparam=poe_fan_temp0=52000'
    - lineinfile:
        path: /boot/firmware/usercfg.txt
        state: present
        regexp: '^dtparam=poe_fan_temp1'
        line: 'dtparam=poe_fan_temp1=58000'
    - lineinfile:
        path: /boot/firmware/usercfg.txt
        state: present
        regexp: '^dtparam=poe_fan_temp2'
        line: 'dtparam=poe_fan_temp2=64000'
    - lineinfile:
        path: /boot/firmware/usercfg.txt
        state: present
        regexp: '^dtparam=poe_fan_temp3'
        line: 'dtparam=poe_fan_temp3=68000'        